<?php
include_once("../inc/config.inc.php");
include_once("conexion.Class.php");
Class dbValidaciones extends Conexion{
	function listaDiasValidadosPorUnidad($year, $month){
		$fecha = $year . "-" . $month ."-01";
		$sql = "SELECT 
					 DATA.ANO
					,DATA.MES
					,DATA.ZONA_DESCRIPCION
					,DATA.PREFECTURA_DESCRIPCION
					,DATA.COMISARIA_DESCRIPCION
					,DATA.UNI_DESCRIPCION
					,DATA.CANTIDAD_DIAS_VALIDADOS
					,DATA.CANTIDAD_DIAS_SIN_VALIDAR
				FROM
				(
					SELECT
						SERVICIOS_CERTIFICADO_VISTA.ANO
						,SERVICIOS_CERTIFICADO_VISTA.MES
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.ZONA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.PREFECTURA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.COMISARIA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_DESCRIPCION
						,count(*) AS CANTIDAD_DIAS_VALIDADOS
					,abs(count(*)- DAY(LAST_DAY( '{$fecha}' ))) AS CANTIDAD_DIAS_SIN_VALIDAR
					FROM
					(
						SELECT DISTINCT
							year(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) AS ANO,
							month(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) AS MES,
							SERVICIOS_CERTIFICADO.`UNI_CODIGO`,
							SERVICIOS_CERTIFICADO.`FECHA_SERVICIOS`
					FROM SERVICIOS_CERTIFICADO
					WHERE
							year(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) =  {$year} AND 
							month(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) = {$month}
					) AS SERVICIOS_CERTIFICADO_VISTA
					INNER JOIN VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS ON (SERVICIOS_CERTIFICADO_VISTA.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_CODIGO)
					GROUP BY
						SERVICIOS_CERTIFICADO_VISTA.ANO
						,SERVICIOS_CERTIFICADO_VISTA.MES
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.ZONA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.PREFECTURA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.COMISARIA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_DESCRIPCION
				
					UNION
				
					SELECT
					     {$year} ANO
						,{$month} MES
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.ZONA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.PREFECTURA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.COMISARIA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_DESCRIPCION
						,0 AS CANTIDAD_DIAS_VALIDADOS
					,ABS(0 - DAY(LAST_DAY( '{$fecha}' ))) AS CANTIDAD_DIAS_SIN_VALIDAR
					FROM
					(
						SELECT DISTINCT
							year(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) AS ANO,
							month(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) AS MES,
							SERVICIOS_CERTIFICADO.`UNI_CODIGO`,
							SERVICIOS_CERTIFICADO.`FECHA_SERVICIOS`
					FROM SERVICIOS_CERTIFICADO
					WHERE
							year(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) = {$year} AND 
							month(SERVICIOS_CERTIFICADO.FECHA_SERVICIOS) = {$month}
					) AS SERVICIOS_CERTIFICADO_VISTA
					RIGHT OUTER JOIN VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS ON (SERVICIOS_CERTIFICADO_VISTA.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_CODIGO)
					WHERE SERVICIOS_CERTIFICADO_VISTA.FECHA_SERVICIOS IS NULL AND VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_CAPTURA = 1
					GROUP BY
						SERVICIOS_CERTIFICADO_VISTA.ANO
						,SERVICIOS_CERTIFICADO_VISTA.MES
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.ZONA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.PREFECTURA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.COMISARIA_DESCRIPCION
						,VISTA_ARBOL_UNIDADES_NACIONAL_CON_PREFECTURAS.UNI_DESCRIPCION
				) DATA
				WHERE DATA.CANTIDAD_DIAS_SIN_VALIDAR > 0
				ORDER BY
					DATA.CANTIDAD_DIAS_SIN_VALIDAR DESC";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaDiasValidados = array();
		$sinDiasValidados = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaDiasValidados, array(
			"year" 							=> $myrow["ANO"],	
			"mes" 							=> $myrow["MES"],	
			"ZonaServicio" 					=> utf8_encode($myrow["ZONA_DESCRIPCION"]),
			"PrefecturaServicio"			=> utf8_encode($myrow["PREFECTURA_DESCRIPCION"]),
			"ComisariaServicio" 			=> utf8_encode($myrow["COMISARIA_DESCRIPCION"]),
			"DestacamentoServicio" 			=> utf8_encode($myrow["UNI_DESCRIPCION"]),
			"cantidadDiasValidados" 		=> $myrow["CANTIDAD_DIAS_VALIDADOS"]*1,
			"cantidadDiasSinValidar" 		=> $myrow["CANTIDAD_DIAS_SIN_VALIDAR"]*1
			));
			if($myrow["EXISTE"]<>true) $sinDiasValidados = false;
		}
		return $sinDiasValidados ? array("data" => false) : array("data" => $listaDiasValidados);
	}
}