<?php
include_once("../inc/config.inc.php");
include_once("conexion.Class.php");
Class dbVehiculo extends Conexion{
	function listaEstadoVehiculos($fecha){
  	$sql = "SELECT 
						  VISTA_ARBOL_UNIDADES_NACIONAL.ZONA_DESCRIPCION AS ZONA,
						  VISTA_ARBOL_UNIDADES_NACIONAL.PREFECTURA_DESCRIPCION AS PREFECTURA,
						  VISTA_ARBOL_UNIDADES_NACIONAL.DEPENDIENTE_DESCRIPCION AS COMISARIA,
						  VISTA_ARBOL_UNIDADES_NACIONAL.UNI_DESCRIPCION AS DESTACAMENTO,
						  VEHICULO.VEH_PATENTE AS PATENTE,
						  VEHICULO.VEH_NUMEROINSITUCIONAL AS SIGLA_INSTITUCIONAL,
						  VEHICULO.VEH_SAP AS SAP,
						  VEHICULO.VEH_BCU AS BCU,
						  TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
						  MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
						  IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
						  ESTADO_VEHICULO.FECHA_DESDE AS FECHA_ESTADO,
						  ESTADO.EST_DESCRIPCION AS ESTADO_ACTUAL,
						  UNIDAD1.UNI_DESCRIPCION AS UNIDAD_AGREGADO
						FROM
						  ESTADO_VEHICULO
						  INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
						  INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
						  LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
						  INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
						  LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
						  INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
						  INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
						  INNER JOIN VISTA_ARBOL_UNIDADES_NACIONAL ON (UNIDAD.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL.UNI_CODIGO)
						WHERE
						  ESTADO_VEHICULO.FECHA_DESDE <= '".$fecha."' AND 
						  (ESTADO_VEHICULO.FECHA_HASTA > '".$fecha."' OR ESTADO_VEHICULO.FECHA_HASTA IS NULL) AND 
						  ESTADO.EST_CODIGO NOT IN (3500) 
						UNION
						SELECT 
						  UNIDAD2.UNI_DESCRIPCION AS ZONA,
						  UNIDAD.UNI_DESCRIPCION AS PREFECTURA,
						  UNIDAD.UNI_DESCRIPCION AS COMISARIA,
						  UNIDAD.UNI_DESCRIPCION AS DESTACAMENTO,
						  VEHICULO.VEH_PATENTE AS PATENTE,
						  VEHICULO.VEH_NUMEROINSITUCIONAL AS SIGLA_INSTITUCIONAL,
						  VEHICULO.VEH_SAP AS SAP,
						  VEHICULO.VEH_BCU AS BCU,
						  TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
						  MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
						  IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
						  ESTADO_VEHICULO.FECHA_DESDE AS FECHA_ESTADO,
						  ESTADO.EST_DESCRIPCION AS ESTADO_ACTUAL,
						  UNIDAD1.UNI_DESCRIPCION AS UNIDAD_AGREGADO
						FROM
						  ESTADO_VEHICULO
						  INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
						  INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
						  LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
						  INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
						  LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
						  INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
						  INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
						  LEFT OUTER JOIN VISTA_ARBOL_UNIDADES_NACIONAL ON (UNIDAD.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL.UNI_CODIGO)
						  INNER JOIN UNIDAD UNIDAD2 ON (UNIDAD.UNI_PADRE = UNIDAD2.UNI_CODIGO)
						WHERE
						  ESTADO_VEHICULO.FECHA_DESDE <= '".$fecha."' AND 
						  (ESTADO_VEHICULO.FECHA_HASTA > '".$fecha."' OR  ESTADO_VEHICULO.FECHA_HASTA IS NULL) AND 
						  ESTADO.EST_CODIGO NOT IN (3500) AND 
						  VISTA_ARBOL_UNIDADES_NACIONAL.ZONA_DESCRIPCION IS NULL
						  AND UNIDAD.UNI_CODIGO <> 1";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaEstadoVehiculos = array();
		while($myrow = mysql_fetch_array($result)){
			array_push($listaEstadoVehiculos, array(
    			"ZONA" 								=> utf8_encode($myrow["ZONA"]),
    			"PREFECTURA"						=> utf8_encode($myrow["PREFECTURA"]),
   				"COMISARIA" 						=> utf8_encode($myrow["COMISARIA"]),
   				"DESTACAMENTO" 						=> utf8_encode($myrow["DESTACAMENTO"]),
				"PATENTE" 							=> utf8_encode($myrow["PATENTE"]),
				"SIGLA_INSTITUCIONAL" 				=> utf8_encode($myrow["SIGLA_INSTITUCIONAL"]),
				"SAP" 								=> utf8_encode($myrow["SAP"]),
				"BCU" 								=> utf8_encode($myrow["BCU"]),
				"TIPO_VEHICULO" 					=> utf8_encode($myrow["TIPO_VEHICULO"]),
				"MARCA" 							=> utf8_encode($myrow["MARCA"]),
				"MODELO" 							=> utf8_encode($myrow["MODELO"]),
				"FECHA_ESTADO" 						=> utf8_encode($myrow["FECHA_ESTADO"]),
				"ESTADO_ACTUAL" 					=> utf8_encode($myrow["ESTADO_ACTUAL"]),
				"UNIDAD_AGREGADO" 					=> utf8_encode($myrow["UNIDAD_AGREGADO"])
			));
		}
		return array("data" => $listaEstadoVehiculos);
	}
	function listaEstadoVehiculosDINAOPERPOL($fecha){
		$sql = "SELECT 
					VISTA_ARBOL_UNIDADES_NACIONAL.ZONA_DESCRIPCION AS ZONA,
					VISTA_ARBOL_UNIDADES_NACIONAL.PREFECTURA_DESCRIPCION AS PREFECTURA,
					VISTA_ARBOL_UNIDADES_NACIONAL.DEPENDIENTE_DESCRIPCION AS COMISARIA,
					VISTA_ARBOL_UNIDADES_NACIONAL.UNI_DESCRIPCION AS DESTACAMENTO,
					VEHICULO.VEH_PATENTE AS DATO_ANTIGUO_PATENTE,
					VEHICULO.VEH_NUMEROINSITUCIONAL AS DATO_ANTIGUO_SIGLA_INSTITUCIONAL,
					VEHICULO.VEH_SAP AS DATO_ANTIGUO_SAP,
					VEHICULO.VEH_BCU AS DATO_ANTIGUO_BCU,
					TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
					MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
					IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
					ESTADO_VEHICULO.FECHA_DESDE AS FECHA_ESTADO,
					ESTADO.EST_DESCRIPCION AS ESTADO_ACTUAL,
					UNIDAD1.UNI_DESCRIPCION AS UNIDAD_AGREGADO,
					VEHICULO.ANNO_FABRICACION ANO_FABRICACION,
					UCASE(PROCEDENCIA_RECURSO.PREC_DESCRIPCION) PROCEDENCIA,
					TIPO_CLASIFICACION_CITACION.TCLASIFICACION_CITACION_DESCRIPCION CAUSA_DE_NO_DISPONIBILIDAD,
					LUGAR_REPARACION.LREP_DESCRIPCION LUGAR,
					VEHICULO.VEH_SIGLA_INSTITUCIONAL,
					VEHICULO.VEH_PPU,
					VEHICULO.VEH_COD_ACTIVO_SAP,
					VEHICULO.VEH_COD_EQUIPO_SAP  
				FROM
					ESTADO_VEHICULO
					INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
					INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
					LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
					INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
					LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
					INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
					INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
					INNER JOIN VISTA_ARBOL_UNIDADES_NACIONAL ON (UNIDAD.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL.UNI_CODIGO)
					INNER JOIN PROCEDENCIA_RECURSO ON (VEHICULO.PREC_CODIGO = PROCEDENCIA_RECURSO.PREC_CODIGO)
					LEFT OUTER JOIN TIPO_CLASIFICACION_CITACION ON (ESTADO_VEHICULO.TCLASIFICACION_CITACION_CODIGO = TIPO_CLASIFICACION_CITACION.TCLASIFICACION_CITACION_CODIGO)
					LEFT OUTER JOIN LUGAR_REPARACION ON (ESTADO_VEHICULO.EST_LUGARREPARACION = LUGAR_REPARACION.LREP_CODIGO)
				WHERE
					ESTADO_VEHICULO.FECHA_DESDE <= '".$fecha."' AND 
					(ESTADO_VEHICULO.FECHA_HASTA > '".$fecha."' OR ESTADO_VEHICULO.FECHA_HASTA IS NULL) AND 
					ESTADO.EST_CODIGO NOT IN (3500,100) 
				UNION
				SELECT 
					UNIDAD2.UNI_DESCRIPCION AS ZONA,
					UNIDAD.UNI_DESCRIPCION AS PREFECTURA,
					UNIDAD.UNI_DESCRIPCION AS COMISARIA,
					UNIDAD.UNI_DESCRIPCION AS DESTACAMENTO,
					VEHICULO.VEH_PATENTE AS DATO_ANTIGUO_PATENTE,
					VEHICULO.VEH_NUMEROINSITUCIONAL AS DATO_ANTIGUO_SIGLA_INSTITUCIONAL,
					VEHICULO.VEH_SAP AS DATO_ANTIGUO_SAP,
					VEHICULO.VEH_BCU AS DATO_ANTIGUO_BCU,
					TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
					MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
					IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
					ESTADO_VEHICULO.FECHA_DESDE AS FECHA_ESTADO,
					ESTADO.EST_DESCRIPCION AS ESTADO_ACTUAL,
					UNIDAD1.UNI_DESCRIPCION AS UNIDAD_AGREGADO,
					VEHICULO.ANNO_FABRICACION ANO_FABRICACION,
					UCASE(PROCEDENCIA_RECURSO.PREC_DESCRIPCION) PROCEDENCIA,
					TIPO_CLASIFICACION_CITACION.TCLASIFICACION_CITACION_DESCRIPCION CAUSA_DE_NO_DISPONIBILIDAD,
					LUGAR_REPARACION.LREP_DESCRIPCION LUGAR,
					VEHICULO.VEH_SIGLA_INSTITUCIONAL,
					VEHICULO.VEH_PPU,
					VEHICULO.VEH_COD_ACTIVO_SAP,
					VEHICULO.VEH_COD_EQUIPO_SAP
				FROM
					ESTADO_VEHICULO
					INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
					INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
					LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
					INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
					LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
					INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
					INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
					LEFT OUTER JOIN VISTA_ARBOL_UNIDADES_NACIONAL ON (UNIDAD.UNI_CODIGO = VISTA_ARBOL_UNIDADES_NACIONAL.UNI_CODIGO)
					INNER JOIN UNIDAD UNIDAD2 ON (UNIDAD.UNI_PADRE = UNIDAD2.UNI_CODIGO)
					INNER JOIN PROCEDENCIA_RECURSO ON (VEHICULO.PREC_CODIGO = PROCEDENCIA_RECURSO.PREC_CODIGO)
					LEFT OUTER JOIN TIPO_CLASIFICACION_CITACION ON (ESTADO_VEHICULO.TCLASIFICACION_CITACION_CODIGO = TIPO_CLASIFICACION_CITACION.TCLASIFICACION_CITACION_CODIGO)
					LEFT OUTER JOIN LUGAR_REPARACION ON (ESTADO_VEHICULO.EST_LUGARREPARACION = LUGAR_REPARACION.LREP_CODIGO)
				WHERE
					ESTADO_VEHICULO.FECHA_DESDE <= '".$fecha."' AND 
					(ESTADO_VEHICULO.FECHA_HASTA > '".$fecha."' OR  ESTADO_VEHICULO.FECHA_HASTA IS NULL) AND 
					ESTADO.EST_CODIGO NOT IN (3500, 100) AND 
					VISTA_ARBOL_UNIDADES_NACIONAL.ZONA_DESCRIPCION IS NULL
					AND UNIDAD.UNI_CODIGO <> 1";
		  $result = $this->execute($this->conect(),$sql);
		  mysql_close();
		  $listaEstadoVehiculosDINAOPERPOL = array();
		  while($myrow = mysql_fetch_array($result)){
			  array_push($listaEstadoVehiculosDINAOPERPOL, array(
				 	"ZONA" 									=> utf8_encode($myrow["ZONA"]),
				  	"PREFECTURA"							=> utf8_encode($myrow["PREFECTURA"]),
					"COMISARIA" 							=> utf8_encode($myrow["COMISARIA"]),
					"DESTACAMENTO" 							=> utf8_encode($myrow["DESTACAMENTO"]),
				  	"DATO_ANTIGUO_PATENTE" 					=> utf8_encode($myrow["DATO_ANTIGUO_PATENTE"]),
				  	"DATO_ANTIGUO_SIGLA_INSTITUCIONAL" 		=> utf8_encode($myrow["DATO_ANTIGUO_SIGLA_INSTITUCIONAL"]),
				  	"DATO_ANTIGUO_SAP" 						=> utf8_encode($myrow["DATO_ANTIGUO_SAP"]),
				  	"DATO_ANTIGUO_BCU" 						=> utf8_encode($myrow["DATO_ANTIGUO_BCU"]),
				  	"TIPO_VEHICULO" 						=> utf8_encode($myrow["TIPO_VEHICULO"]),
				  	"MARCA" 								=> utf8_encode($myrow["MARCA"]),
				  	"MODELO" 								=> utf8_encode($myrow["MODELO"]),
				  	"FECHA_ESTADO" 							=> utf8_encode($myrow["FECHA_ESTADO"]),
				  	"ESTADO_ACTUAL" 						=> utf8_encode($myrow["ESTADO_ACTUAL"]),
				  	"UNIDAD_AGREGADO" 						=> utf8_encode($myrow["UNIDAD_AGREGADO"]),
					"ANO_FABRICACION" 						=> utf8_encode($myrow["ANO_FABRICACION"]),
				  	"PROCEDENCIA" 							=> utf8_encode($myrow["PROCEDENCIA"]),
				  	"CAUSA_DE_NO_DISPONIBILIDAD" 			=> utf8_encode($myrow["CAUSA_DE_NO_DISPONIBILIDAD"]),
				  	"LUGAR" 								=> utf8_encode($myrow["LUGAR"]),
					"VEH_SIGLA_INSTITUCIONAL" 				=> utf8_encode($myrow["VEH_SIGLA_INSTITUCIONAL"]),
				  	"VEH_PPU" 								=> utf8_encode($myrow["VEH_PPU"]),
				  	"VEH_COD_ACTIVO_SAP" 					=> utf8_encode($myrow["VEH_COD_ACTIVO_SAP"]),
				  	"VEH_COD_EQUIPO_SAP" 					=> utf8_encode($myrow["VEH_COD_EQUIPO_SAP"])
			  ));
		  }
		  return array("data" => $listaEstadoVehiculosDINAOPERPOL);
	  }
/*funcionanes implementadas para api de portal de consultas*/
	  function buscarVehiculoPorCodigo_o_Patente($tipoBusqueda, $parametroBusqueda){
		$sql = "SELECT
					VEHICULO.VEH_CODIGO, 
					VEHICULO.VEH_COD_EQUIPO_SAP,
					TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
					MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
					IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
					/*IF(ISNULL(VEHICULO.VEH_PPU), VEHICULO.VEH_PATENTE, VEHICULO.VEH_PPU) PATENTE*/
					VEHICULO.VEH_PATENTE PATENTE
				FROM VEHICULO 
				INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
				LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
				INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
				WHERE
					VEHICULO.VEH_COD_EQUIPO_SAP = '{$parametroBusqueda}'";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaVehiculos = array();
		$sinVehiculo = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaVehiculos, array(
				"VEH_CODIGO" 			=> $myrow["VEH_CODIGO"],
				"VEH_CODIGO_EQUIPO" 	=> $myrow["VEH_COD_EQUIPO_SAP"],
				"TIPO_VEHICULO"			=> $myrow["TIPO_VEHICULO"],
				"MARCA_VEHICULO" 		=> $myrow["MARCA"],
				"MODELO_VEHICULO" 		=> $myrow["MODELO"],
				"PATENTE" 				=> $myrow["PATENTE"]
			));
			if($myrow["EXISTE"]<>true) $sinVehiculo = false;
		}
		return $sinVehiculo ? array("data" => false) : array("data" => $listaVehiculos);
	}
	function buscarVehiculoPorParametros($tipoVehiculo, $marcaVehiculo, $modeloVehiculo, $patente, $incluirDeBaja){
		$sql = "SELECT 
						VEHICULO.VEH_CODIGO,
						VEHICULO.VEH_COD_EQUIPO_SAP,
						TIPO_VEHICULO.TVEH_DESCRIPCION, 
						MARCA_VEHICULO.MVEH_DESCRIPCION,
						IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
						VEHICULO.VEH_PATENTE, 
						UNIDAD.UNI_DESCRIPCION, 
						ESTADO.EST_DESCRIPCION,
						IF(ESTADO_VEHICULO.UNI_AGREGADO,CONCAT(ESTADO.EST_DESCRIPCION,' A ', UNIDAD1.UNI_DESCRIPCION),ESTADO.EST_DESCRIPCION) ESTADO_ACTUAL,
						ESTADO_VEHICULO.FECHA_DESDE
				FROM ESTADO_VEHICULO
				INNER JOIN (
						SELECT ESTADO_VEHICULO.VEH_CODIGO, MAX(ESTADO_VEHICULO.CORRELATIVO_ESTADOVEHICULO) ULTIMO_CORRELATIVO
						FROM ESTADO_VEHICULO 
						INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
						GROUP BY  ESTADO_VEHICULO.VEH_CODIGO
				) AS ULTIMO_ESTADO
				ON (ESTADO_VEHICULO.VEH_CODIGO = ULTIMO_ESTADO.VEH_CODIGO AND ESTADO_VEHICULO.CORRELATIVO_ESTADOVEHICULO = ULTIMO_ESTADO.ULTIMO_CORRELATIVO)
				INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
				INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
				INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
				INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
				INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
				LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
				LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
				WHERE 1";
		if ($tipoVehiculo <> "") 		$sql .= " AND VEHICULO.TVEH_CODIGO = {$tipoVehiculo}";
		if ($marcaVehiculo <> "") 		$sql .= " AND VEHICULO.MVEH_CODIGO = {$marcaVehiculo}";
		if ($patente <> "") 			$sql .= " AND VEHICULO.VEH_PATENTE = '{$patente}'";
		if ($incluirDeBaja == "false")	$sql .= " AND ESTADO_VEHICULO.EST_CODIGO NOT IN (100)";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaVehiculos = array();
		$sinVehiculo = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaVehiculos, array(
				"VEH_CODIGO" 			=> $myrow["VEH_CODIGO"],
				"VEH_CODIGO_EQUIPO" 	=> $myrow["VEH_COD_EQUIPO_SAP"],
				"TIPO_VEHICULO"			=> $myrow["TVEH_DESCRIPCION"],
				"MARCA_VEHICULO" 		=> $myrow["MVEH_DESCRIPCION"],
				"MODELO_VEHICULO" 		=> $myrow["MODELO"],
				"PATENTE" 				=> $myrow["VEH_PATENTE"],
				"UNIDAD" 				=> utf8_encode($myrow["UNI_DESCRIPCION"]),
				"ESTADO_ACTUAL" 		=> utf8_encode($myrow["ESTADO_ACTUAL"]),
				"ESTADO_ACTUAL_DESDE"	=> $myrow["FECHA_DESDE"]
			));
			if($myrow["EXISTE"]<>true) $sinVehiculo = false;
		}
		return $sinVehiculo ? array("data" => false) : array("data" => $listaVehiculos);
	}
	function buscarVehiculoPorUnidad($codigoUnidad, $fecha){
		$sql = "SELECT 
					DATA.VEH_CODIGO,
					DATA.VEH_COD_EQUIPO_SAP,
					DATA.TIPO_VEHICULO,
					DATA.MARCA,
					DATA.MODELO,
					DATA.VEH_PATENTE,
					DATA.UNI_DESCRIPCION,
					DATA.ESTADO,
					DATA.FECHA
				FROM
				(
				SELECT 
					VEHICULO.VEH_CODIGO,
					VEHICULO.VEH_COD_EQUIPO_SAP,
					TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
					MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
					IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
					VEHICULO.VEH_PATENTE, 
					UNIDAD.UNI_DESCRIPCION,
					IF(ESTADO_VEHICULO.UNI_AGREGADO,CONCAT(ESTADO.EST_DESCRIPCION,' A ', UNIDAD1.UNI_DESCRIPCION),ESTADO.EST_DESCRIPCION) ESTADO,
					MARCELO_FECHA.FECHA
				FROM
				ESTADO_VEHICULO
				INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
				INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
				LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
				INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
				LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
				INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
				INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
				INNER JOIN MARCELO_FECHA ON (ESTADO_VEHICULO.FECHA_DESDE <= MARCELO_FECHA.FECHA AND (ESTADO_VEHICULO.FECHA_HASTA > MARCELO_FECHA.FECHA OR ESTADO_VEHICULO.`FECHA_HASTA` IS NULL))
				WHERE
					MARCELO_FECHA.FECHA =  '{$fecha}' AND 
					ESTADO_VEHICULO.UNI_CODIGO = {$codigoUnidad} AND
					ESTADO.EST_CODIGO NOT IN (3500) 
				UNION 
				SELECT 
					VEHICULO.VEH_CODIGO,
					VEHICULO.VEH_COD_EQUIPO_SAP,
					TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
					MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
					IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
					VEHICULO.VEH_PATENTE, 
					UNIDAD1.UNI_DESCRIPCION,
					IF(ESTADO_VEHICULO.UNI_AGREGADO,CONCAT(ESTADO.EST_DESCRIPCION,' DESDE ', UNIDAD.UNI_DESCRIPCION),UNIDAD.UNI_DESCRIPCION) ESTADO,
					MARCELO_FECHA.FECHA
				FROM
				ESTADO_VEHICULO
				INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
				INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
				LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
				INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
				LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
				INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
				INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
				INNER JOIN MARCELO_FECHA ON (ESTADO_VEHICULO.FECHA_DESDE <= MARCELO_FECHA.FECHA AND (ESTADO_VEHICULO.FECHA_HASTA > MARCELO_FECHA.FECHA OR ESTADO_VEHICULO.`FECHA_HASTA` IS NULL))
				WHERE
					MARCELO_FECHA.FECHA =  '{$fecha}' AND 
					ESTADO_VEHICULO.UNI_AGREGADO = {$codigoUnidad}
				) DATA
				ORDER BY DATA.UNI_DESCRIPCION, DATA.TIPO_VEHICULO, DATA.MARCA, DATA.MODELO";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaVehiculos = array();
		$sinVehiculo = true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaVehiculos, array(
				"VEH_CODIGO" 			=> $myrow["VEH_CODIGO"],
				"VEH_CODIGO_EQUIPO" 	=> $myrow["VEH_COD_EQUIPO_SAP"],
				"TIPO_VEHICULO"			=> $myrow["TIPO_VEHICULO"],
				"MARCA_VEHICULO" 		=> $myrow["MARCA"],
				"MODELO_VEHICULO" 		=> $myrow["MODELO"],
				"PATENTE" 				=> $myrow["VEH_PATENTE"],
				"UNIDAD" 				=> utf8_encode($myrow["UNI_DESCRIPCION"]),
				"ESTADO" 				=> utf8_encode($myrow["ESTADO"]),
				"FECHA"					=> $myrow["FECHA"]
			));
			if($myrow["EXISTE"]<>true) $sinVehiculo = false;
		}
		return $sinVehiculo ? array("data" => false) : array("data" => $listaVehiculos);
	}
	function serviciosVehiculooPorCodigoDeVehiculo($codigoVehiculo, $fechaDesde, $fechaHasta){
		$sql = "SELECT DISTINCT
					VEHICULO.VEH_CODIGO,
					VEHICULO.VEH_COD_EQUIPO_SAP,
					TIPO_VEHICULO.TVEH_DESCRIPCION,
					MARCA_VEHICULO.MVEH_DESCRIPCION,
					MODELO_VEHICULO.MODVEH_DESCRIPCION,
					VEHICULO.VEH_PATENTE,
					SERVICIO.FECHA,
					UPPER(TIPO_SERVICIO.TSERV_DESCRIPCION) AS  TIPO_SERVICIO,
					UCASE(TIPO_EXTRAORDINARIO.TEXT_DESCRIPCION) TIPOEXTRAORDINARIO,
					SERVICIO.HORA_INICIO,
					SERVICIO.HORA_TERMINO,
					VEHICULO_SERVICIO.KM_INICIAL,
					VEHICULO_SERVICIO.KM_FINAL,
					UNIDAD.UNI_DESCRIPCION
				FROM
				UNIDAD
				INNER JOIN SERVICIO ON (UNIDAD.UNI_CODIGO = SERVICIO.UNI_CODIGO)
				INNER JOIN TIPO_SERVICIO ON (SERVICIO.TSERV_CODIGO = TIPO_SERVICIO.TSERV_CODIGO)
				INNER JOIN FUNCIONARIO_SERVICIO ON (SERVICIO.UNI_CODIGO = FUNCIONARIO_SERVICIO.UNI_CODIGO)
				AND (SERVICIO.CORRELATIVO_SERVICIO = FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO)
				INNER JOIN FUNCIONARIO_VEHICULO ON (FUNCIONARIO_SERVICIO.UNI_CODIGO = FUNCIONARIO_VEHICULO.FUN_UNI_CODIGO)
				AND (FUNCIONARIO_SERVICIO.CORRELATIVO_SERVICIO = FUNCIONARIO_VEHICULO.FUN_CORRELATIVO_SERVICIO)
				AND (FUNCIONARIO_SERVICIO.FUN_CODIGO = FUNCIONARIO_VEHICULO.FUN_CODIGO)
				INNER JOIN VEHICULO_SERVICIO ON (FUNCIONARIO_VEHICULO.VEH_UNI_CODIGO = VEHICULO_SERVICIO.UNI_CODIGO)
				AND (FUNCIONARIO_VEHICULO.VEH_CORRELATIVO_SERVICIO = VEHICULO_SERVICIO.CORRELATIVO_SERVICIO)
				AND (FUNCIONARIO_VEHICULO.VEH_CODIGO = VEHICULO_SERVICIO.VEH_CODIGO)
				INNER JOIN VEHICULO ON (VEHICULO_SERVICIO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
				INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
				INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
				INNER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
				LEFT OUTER JOIN TIPO_EXTRAORDINARIO ON (SERVICIO.TEXT_CODIGO = TIPO_EXTRAORDINARIO.TEXT_CODIGO)
				WHERE VEHICULO.VEH_CODIGO = '{$codigoVehiculo}' AND SERVICIO.FECHA BETWEEN '{$fechaDesde}' AND '{$fechaHasta}'
				ORDER BY SERVICIO.FECHA, SERVICIO.HORA_INICIO";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaServicios = array();
		$sinServicio = true;
		$servicioRealizado = "";
		$fecha_actual = date("d-m-Y H:i:s"); 
		while($myrow = mysql_fetch_array($result)){
			if ($myrow["TIPOEXTRAORDINARIO"] == "") $servicioRealizado = utf8_encode($myrow["TIPO_SERVICIO"]);
			else $servicioRealizado = utf8_encode($myrow["TIPO_SERVICIO"]) . " (" . utf8_encode($myrow["TIPOEXTRAORDINARIO"]) .")";
			array_push($listaServicios, array(
				"codigoVehiculo"		=> $myrow["VEH_CODIGO"],
				"codigoEquipoSAP" 		=> $myrow["VEH_COD_EQUIPO_SAP"],
				"tipoVehiculo"			=> $myrow["TVEH_DESCRIPCION"],
				"marcaVehiculo" 		=> $myrow["MVEH_DESCRIPCION"], //date('d-m-Y', strtotime($myrow["FECHA"])), 
				"modeloVehiculo" 		=> $myrow["MODVEH_DESCRIPCION"],
				"pantenteVehiculo"		=> $myrow["VEH_PATENTE"],
				"fechaServicio"			=> $myrow["FECHA"],
				"servicio"				=> $servicioRealizado, //$myrow["TIPO_SERVICIO"],
				"horaInicio" 			=> $myrow["HORA_INICIO"],
				"horaTermino" 			=> $myrow["HORA_TERMINO"],
				"kmInicial" 			=> $myrow["KM_INICIAL"],
				"kmFinal" 				=> $myrow["KM_FINAL"],
				"destacamento" 			=> utf8_encode($myrow["UNI_DESCRIPCION"]),
				"fechaHoraConsulta"		=> $fecha_actual
			));
			if($myrow["EXISTE"]<>true) $sinServicio = false;
		}
		return $sinServicio ? array("data" => false) : array("data" => $listaServicios);
	}
	function estadoVehiculoPorCodigo($codigoVehiculo, $fechaDesde, $fechaHasta){
		$sql = "SELECT 
					VEHICULO.VEH_CODIGO,
					TIPO_VEHICULO.TVEH_DESCRIPCION AS TIPO_VEHICULO,
					MARCA_VEHICULO.MVEH_DESCRIPCION AS MARCA,
					IF(MODELO_VEHICULO.MODVEH_DESCRIPCION IS NULL, 'NO INDICA MODELO', MODELO_VEHICULO.MODVEH_DESCRIPCION) AS MODELO,
					/*ESTADO_VEHICULO.FECHA_DESDE AS FECHA_ESTADO,*/
					IF(ISNULL(VEHICULO.VEH_PPU), VEHICULO.VEH_PATENTE, VEHICULO.VEH_PPU) PATENTE,
					IF(ISNULL(VEHICULO.VEH_SIGLA_INSTITUCIONAL), VEHICULO.VEH_NUMEROINSITUCIONAL, VEHICULO.VEH_SIGLA_INSTITUCIONAL) SIGLA_INSTITUCIONAL,
					ESTADO_VEHICULO.FECHA_DESDE,
					ESTADO_VEHICULO.FECHA_HASTA,
					IF(ESTADO_VEHICULO.EST_CODIGO = 100,ESTADO_VEHICULO.FECHA_HASTA,DATE_ADD(ESTADO_VEHICULO.FECHA_HASTA, interval -1 DAY)) FECHA_HASTA_MOSTRAR,
					UNIDAD.UNI_DESCRIPCION,
					IF(ESTADO_VEHICULO.UNI_AGREGADO,CONCAT(ESTADO.EST_DESCRIPCION,' A ', UNIDAD1.UNI_DESCRIPCION),ESTADO.EST_DESCRIPCION) ESTADO
				FROM
					ESTADO_VEHICULO
					INNER JOIN ESTADO ON (ESTADO_VEHICULO.EST_CODIGO = ESTADO.EST_CODIGO)
					INNER JOIN VEHICULO ON (ESTADO_VEHICULO.VEH_CODIGO = VEHICULO.VEH_CODIGO)
					LEFT OUTER JOIN UNIDAD UNIDAD1 ON (ESTADO_VEHICULO.UNI_AGREGADO = UNIDAD1.UNI_CODIGO)
					INNER JOIN TIPO_VEHICULO ON (VEHICULO.TVEH_CODIGO = TIPO_VEHICULO.TVEH_CODIGO)
					LEFT OUTER JOIN MODELO_VEHICULO ON (VEHICULO.MODVEH_CODIGO = MODELO_VEHICULO.MODVEH_CODIGO)
					INNER JOIN MARCA_VEHICULO ON (VEHICULO.MVEH_CODIGO = MARCA_VEHICULO.MVEH_CODIGO)
					INNER JOIN UNIDAD ON (ESTADO_VEHICULO.UNI_CODIGO = UNIDAD.UNI_CODIGO)
				WHERE
					(ESTADO_VEHICULO.VEH_CODIGO = '{$codigoVehiculo}' AND (ESTADO_VEHICULO.FECHA_DESDE <> ESTADO_VEHICULO.FECHA_HASTA OR ESTADO_VEHICULO.FECHA_HASTA IS NULL))
					OR
					(ESTADO_VEHICULO.VEH_CODIGO = '{$codigoVehiculo}' AND ESTADO_VEHICULO.EST_CODIGO = 100)
				ORDER BY ESTADO_VEHICULO.CORRELATIVO_ESTADOVEHICULO DESC";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaEstados 	= array();
		$sinEstado 		= true;
		$fecha_actual = date("d-m-Y H:i:s"); 
		while($myrow = mysql_fetch_array($result)){
			array_push($listaEstados, array(
				"tipoVehiculo"				=> $myrow["TIPO_VEHICULO"],
				"marcaVehiculo" 			=> $myrow["MARCA"],
				"modeloVehiculo"			=> $myrow["MODELO"],
				"pantenteVehiculo"			=> $myrow["PATENTE"],
				"fechaDesde" 				=> $myrow["FECHA_DESDE"],
				"fechaHasta" 				=> $myrow["FECHA_HASTA"],
				"fechaHastamMostrar"		=> $myrow["FECHA_HASTA_MOSTRAR"],
				"estado" 					=> utf8_encode($myrow["ESTADO"]),
				"destacamento" 				=> utf8_encode($myrow["UNI_DESCRIPCION"]),
				"fechaHoraConsulta"			=> $fecha_actual
			));
			if($myrow["EXISTE"]<>true) $sinEstado = false;
		}
		return $sinEstado ? array("data" => false) : array("data" => $listaEstados);
	}
	function listaTiposDeVehiculos(){
		$sql = "SELECT 
					TIPO_VEHICULO.TVEH_CODIGO
				   ,TIPO_VEHICULO.TVEH_DESCRIPCION 
				FROM TIPO_VEHICULO
				ORDER BY TIPO_VEHICULO.TVEH_DESCRIPCION";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaTiposDeVehiculos 	= array();
		$sinTipos 				= true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaTiposDeVehiculos, array(
				"codigoTipoVehiculo"				=> $myrow["TVEH_CODIGO"],
				"descripcionTipoVehiculo" 			=> $myrow["TVEH_DESCRIPCION"]
			));
			if($myrow["EXISTE"]<>true) $sinTipos = false;
		}
		return $sinTipos ? array("data" => false) : array("data" => $listaTiposDeVehiculos);
	}
	function listaMarcasDeVehiculos(){
		$sql = "SELECT 
					MARCA_VEHICULO.MVEH_CODIGO
				   ,MARCA_VEHICULO.MVEH_DESCRIPCION 
				FROM MARCA_VEHICULO
				ORDER BY MARCA_VEHICULO.MVEH_DESCRIPCION";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaMarcasDeVehiculos 	= array();
		$sinMarcas 					= true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaMarcasDeVehiculos, array(
				"codigoMarcaVehiculo"		=> $myrow["MVEH_CODIGO"],
				"descripcionMarcaVehiculo" 	=> $myrow["MVEH_DESCRIPCION"]
			));
			if($myrow["EXISTE"]<>true) $sinMarcas = false;
		}
		return $sinMarcas ? array("data" => false) : array("data" => $listaMarcasDeVehiculos);
	}
	function listaModelosDeVehiculos(){
		$sql = "SELECT 
					MODELO_VEHICULO.MVEH_CODIGO
				   ,MODELO_VEHICULO.MODVEH_CODIGO
				   ,MODELO_VEHICULO.MODVEH_DESCRIPCION
				FROM MODELO_VEHICULO
				ORDER BY
					MODELO_VEHICULO.MODVEH_DESCRIPCION";
		$result = $this->execute($this->conect(),$sql);
		mysql_close();
		$listaModelosDeVehiculos 	= array();
		$sinModelos 				= true;
		while($myrow = mysql_fetch_array($result)){
			array_push($listaModelosDeVehiculos, array(
				"codigoMarcaVehiculo"			=> $myrow["MVEH_CODIGO"],
				"codigoModeloVehiculo"			=> $myrow["MODVEH_CODIGO"],
				"descripcionModeloVehiculo" 	=> $myrow["MODVEH_DESCRIPCION"]
			));
			if($myrow["EXISTE"]<>true) $sinModelos = false;
		}
		return $sinModelos ? array("data" => false) : array("data" => $listaModelosDeVehiculos);
	}
}
